                                                                                                                                                                                                                                         id,
                                                                                                                                                                                                                                                     req.body,
                                                                                                                                                                                                                                                                 { new: true, runValidators: true }
                                                                                                                                                                                                                                                                         );

                                                                                                                                                                                                                                                                                 if (!updatedBook) {
                                                                                                                                                                                                                                                                                             return res.status(404).json({ message: 'Book not found' });
                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                             res.json(updatedBook);
                                                                                                                                                                                                                                                                                                                 } catch (error) {
                                                                                                                                                                                                                                                                                                                         res.status(400).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                             /**
                                                                                                                                                                                                                                                                                                                              * DELETE - Remove a book by ID
                                                                                                                                                                                                                                                                                                                               * DELETE /books/:id
                                                                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                                                                app.delete('/books/:id', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                            const { id } = req.params;

                                                                                                                                                                                                                                                                                                                                                    const deletedBook = await Book.findByIdAndDelete(id);

                                                                                                                                                                                                                                                                                                                                                            if (!deletedBook) {
                                                                                                                                                                                                                                                                                                                                                                        return res.status(404).json({ message: 'Book not found' });
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                        res.json({ message: 'Book deleted successfully', deletedBook });
                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                        // Start the server
                                                                                                                                                                                                                                                                                                                                                                                                        const PORT = process.env.PORT || 8080;
                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`Bookshelf API running at http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                            });