                                                                            }

                                                                            function merge(board) {
                                                                              const newBoard = board.map(row => [...row]);
                                                                                for (let r = 0; r < SIZE; r++) {
                                                                                    for (let c = 0; c < SIZE - 1; c++) {
                                                                                          if (newBoard[r][c] !== 0 && newBoard[r][c] === newBoard[r][c + 1]) {
                                                                                                  newBoard[r][c] *= 2;
                                                                                                          newBoard[r][c + 1] = 0;
                                                                                                                }
                                                                                                                    }
                                                                                                                      }
                                                                                                                        return newBoard;
                                                                                                                        }

                                                                                                                        function moveLeft(board) {
                                                                                                                          let newBoard = compress(board);
                                                                                                                            newBoard = merge(newBoard);
                                                                                                                              newBoard = compress(newBoard);
                                                                                                                                return newBoard;
                                                                                                                                }

                                                                                                                                function moveRight(board) {
                                                                                                                                  let reversed = reverse(board);
                                                                                                                                    let moved = moveLeft(reversed);
                                                                                                                                      return reverse(moved);
                                                                                                                                      }

                                                                                                                                      function moveUp(board) {
                                                                                                                                        let transposed = transpose(board);
                                                                                                                                          let moved = moveLeft(transposed);
                                                                                                                                            return transpose(moved);
                                                                                                                                            }

                                                                                                                                            function moveDown(board) {
                                                                                                                                              let transposed = transpose(board);
                                                                                                                                                let moved = moveRight(transposed);
                                                                                                                                                  return transpose(moved);
                                                                                                                                                  }

                                                                                                                                                  // Implement Game Over Function
                                                                                                                                                  function isGameOver(board) {
                                                                                                                                                    for (let r = 0; r < SIZE; r++) {
                                                                                                                                                        for (let c = 0; c < SIZE; c++) {
                                                                                                                                                              // 1. If any cell is empty, the game is not over
                                                                                                                                                                    if (board[r][c] === 0) return false;

                                                                                                                                                                          // 2. Check horizontally adjacent tile
                                                                                                                                                                                if (c < SIZE - 1 && board[r][c] === board[r][c + 1]) return false;

                                                                                                                                                                                      // 3. Check vertically adjacent tile
                                                                                                                                                                                            if (r < SIZE - 1 && board[r][c] === board[r + 1][c]) return false;
                                                                                                                                                                                                }
                                                                                                                                                                                                  }
                                                                                                                                                                                                    // No empty cells and no available merges left
                                                                                                                                                                                                      return true;
                                                                                                                                                                                                      }

                                                                                                                                                                                                      function App() {
                                                                                                                                                                                                        const [board, setBoard] = useState(() => {
                                                                                                                                                                                                            let newBoard = getEmptyBoard();
                                                                                                                                                                                                                newBoard = addRandomTile(newBoard);
                                                                                                                                                                                                                    newBoard = addRandomTile(newBoard);
                                                                                                                                                                                                                        return newBoard;
                                                                                                                                                                                                                          });

                                                                                                                                                                                                                            const [gameOver, setGameOver] = useState(false);

                                                                                                                                                                                                                              const handleKeyDown = (event) => {
                                                                                                                                                                                                                                  // Prevent moves if game is already over
                                                                                                                                                                                                                                      if (gameOver) return;

                                                                                                                                                                                                                                          let processedBoard;
                                                                                                                                                                                                                                              const currentBoardCopy = board.map(row => [...row]);

                                                                                                                                                                                                                                                  if (event.key === 'ArrowLeft') {
                                                                                                                                                                                                                                                        processedBoard = moveLeft(currentBoardCopy);
                                                                                                                                                                                                                                                            } else if (event.key === 'ArrowRight') {
                                                                                                                                                                                                                                                                  processedBoard = moveRight(currentBoardCopy);
                                                                                                                                                                                                                                                                      } else if (event.key === 'ArrowUp') {
                                                                                                                                                                                                                                                                            processedBoard = moveUp(currentBoardCopy);
                                                                                                                                                                                                                                                                                } else if (event.key === 'ArrowDown') {
                                                                                                                                                                                                                                                                                      processedBoard = moveDown(currentBoardCopy);
                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        // Check if the move changed the board state
                                                                                                                                                                                                                                                                                                            if (JSON.stringify(board) !== JSON.stringify(processedBoard)) {
                                                                                                                                                                                                                                                                                                                  const nextBoard = addRandomTile(processedBoard);
                                                                                                                                                                                                                                                                                                                        setBoard(nextBoard);

                                                                                                                                                                                                                                                                                                                              // Check if the board reached game over state
                                                                                                                                                                                                                                                                                                                                    if (isGameOver(nextBoard)) {
                                                                                                                                                                                                                                                                                                                                            setGameOver(true);
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                          useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                              window.addEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                                                                                  return () => window.removeEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                                                                                    }, [board, gameOver]);

                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                          <div className="container">
                                                                                                                                                                                                                                                                                                                                                                                <h1>2048 Game</h1>
                                                                                                                                                                                                                                                                                                                                                                                      <div className="board">
                                                                                                                                                                                                                                                                                                                                                                                              {board.map((row, rowIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                        <div key={rowIndex} className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                    {row.map((cell, cellIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={cellIndex} className={`cell cell-${cell}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {cell !== 0 ? cell : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {gameOver && <p className="game-over">Game Over</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;