import React, { useState } from 'react';
import { produce } from 'immer';
import './App.css';

const initialEventsData = [
  {
      eventId: 'event1',
          title: 'Coffee with Samantha',
              date: '2023-11-02T12:00:00.000Z',
                  metadata: {
                        invitees: [
                                { name: 'Samantha', email: 'samantha@example.com' }
                                      ]
                                          }
                                            },
                                              {
                                                  eventId: 'event2',
                                                      title: 'Focus time',
                                                          date: '2023-11-02T13:00:00.000Z',
                                                              metadata: {
                                                                    notes: 'Time for me to focus!'
                                                                        }
                                                                          },
                                                                            {
                                                                                eventId: 'event3',
                                                                                    title: 'Team meeting',
                                                                                        date: '2023-11-02T15:00:00.000Z',
                                                                                            metadata: {
                                                                                                  notes: 'Weekly team catch up call!',
                                                                                                        invitees: [
                                                                                                                { name: 'Lois Fahler', email: 'lfahler@widgets.com' },
                                                                                                                        { name: 'Gerarda Nicosmides', email: 'gnicosmides@widgets.com' }, // Target for removal
                                                                                                                                { name: 'Evgit Popova', email: 'epopova@widgets.com' },
                                                                                                                                        { name: 'Envis Geppe', email: 'egeppe@widgets.com' }
                                                                                                                                              ]
                                                                                                                                                  }
                                                                                                                                                    }
                                                                                                                                                    ];

                                                                                                                                                    const getInitialState = () => JSON.parse(JSON.stringify(initialEventsData));

                                                                                                                                                    export default function App() {
                                                                                                                                                      const [events, setEvents] = useState(getInitialState);

                                                                                                                                                        // Method 1: Manual Immutable Update (Verbose)
                                                                                                                                                          const handleRemoveWithManual = () => {
                                                                                                                                                              setEvents((currentEvents) => {
                                                                                                                                                                    return currentEvents.map((event) => {
                                                                                                                                                                            if (event.title === 'Team meeting') {
                                                                                                                                                                                      const originalInvitees = event.metadata.invitees || [];
                                                                                                                                                                                                const inviteeIndex = originalInvitees.findIndex(
                                                                                                                                                                                                            (i) => i.email === 'gnicosmides@widgets.com'
                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                if (inviteeIndex !== -1) {
                                                                                                                                                                                                                                            const newInvitees = [...originalInvitees];
                                                                                                                                                                                                                                                        newInvitees.splice(inviteeIndex, 1);

                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                  ...event,
                                                                                                                                                                                                                                                                                                metadata: {
                                                                                                                                                                                                                                                                                                                ...event.metadata,
                                                                                                                                                                                                                                                                                                                                invitees: newInvitees
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                    return event;
                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                  // Method 2: Update using Immer (Clean & Mutative Syntax)
                                                                                                                                                                                                                                                                                                                                                                                                    const handleRemoveWithImmer = () => {
                                                                                                                                                                                                                                                                                                                                                                                                        setEvents(
                                                                                                                                                                                                                                                                                                                                                                                                              produce((draft) => {
                                                                                                                                                                                                                                                                                                                                                                                                                      const eventToUpdate = draft.find((event) => event.title === 'Team meeting');
                                                                                                                                                                                                                                                                                                                                                                                                                              if (eventToUpdate && eventToUpdate.metadata && eventToUpdate.metadata.invitees) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const inviteeIndex = eventToUpdate.metadata.invitees.findIndex(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    (i) => i.email === 'gnicosmides@widgets.com'
                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (inviteeIndex !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Directly mutate the draft array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                eventToUpdate.metadata.invitees.splice(inviteeIndex, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }