                                                                                                                                                  }

                                                                                                                                                  function isGameOver(board) {
                                                                                                                                                    for (let r = 0; r < SIZE; r++) {
                                                                                                                                                        for (let c = 0; c < SIZE; c++) {
                                                                                                                                                              if (board[r][c] === 0) return false;
                                                                                                                                                                    if (c < SIZE - 1 && board[r][c] === board[r][c + 1]) return false;
                                                                                                                                                                          if (r < SIZE - 1 && board[r][c] === board[r + 1][c]) return false;
                                                                                                                                                                              }
                                                                                                                                                                                }
                                                                                                                                                                                  return true;
                                                                                                                                                                                  }

                                                                                                                                                                                  function App() {
                                                                                                                                                                                    const [board, setBoard] = useState(() => {
                                                                                                                                                                                        let newBoard = getEmptyBoard();
                                                                                                                                                                                            newBoard = addRandomTile(newBoard);
                                                                                                                                                                                                newBoard = addRandomTile(newBoard);
                                                                                                                                                                                                    return newBoard;
                                                                                                                                                                                                      });

                                                                                                                                                                                                        const [gameOver, setGameOver] = useState(false);

                                                                                                                                                                                                          // Restart function to reset state
                                                                                                                                                                                                            const restartGame = () => {
                                                                                                                                                                                                                let newBoard = getEmptyBoard();
                                                                                                                                                                                                                    newBoard = addRandomTile(newBoard);
                                                                                                                                                                                                                        newBoard = addRandomTile(newBoard);
                                                                                                                                                                                                                            setBoard(newBoard);
                                                                                                                                                                                                                                setGameOver(false);
                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                    const handleKeyDown = (e) => {
                                                                                                                                                                                                                                        if (gameOver) return;

                                                                                                                                                                                                                                            let processedBoard;
                                                                                                                                                                                                                                                const currentBoardCopy = board.map(row => [...row]);

                                                                                                                                                                                                                                                    if (e.key === 'ArrowLeft') {
                                                                                                                                                                                                                                                          processedBoard = moveLeft(currentBoardCopy);
                                                                                                                                                                                                                                                              } else if (e.key === 'ArrowRight') {
                                                                                                                                                                                                                                                                    processedBoard = moveRight(currentBoardCopy);
                                                                                                                                                                                                                                                                        } else if (e.key === 'ArrowUp') {
                                                                                                                                                                                                                                                                              processedBoard = moveUp(currentBoardCopy);
                                                                                                                                                                                                                                                                                  } else if (e.key === 'ArrowDown') {
                                                                                                                                                                                                                                                                                        processedBoard = moveDown(currentBoardCopy);
                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                          if (JSON.stringify(board) !== JSON.stringify(processedBoard)) {
                                                                                                                                                                                                                                                                                                                const boardWithNewTile = addRandomTile(processedBoard);
                                                                                                                                                                                                                                                                                                                      setBoard(boardWithNewTile);

                                                                                                                                                                                                                                                                                                                            if (isGameOver(boardWithNewTile)) {
                                                                                                                                                                                                                                                                                                                                    setGameOver(true);
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                      window.addEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                                                                          return () => window.removeEventListener('keydown', handleKeyDown);
                                                                                                                                                                                                                                                                                                                                                            }, [board, gameOver]);

                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                  <div className="container">
                                                                                                                                                                                                                                                                                                                                                                        <h1>2048 Game</h1>
                                                                                                                                                                                                                                                                                                                                                                              <div className="board-container">
                                                                                                                                                                                                                                                                                                                                                                                      <div className="board">
                                                                                                                                                                                                                                                                                                                                                                                                {board.map((row, rowIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                            <div key={rowIndex} className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                          {row.map((cell, cellIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={cellIndex} className={`cell cell-${cell}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {cell !== 0 ? cell : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {gameOver && <div className="game-over">Game Over</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="restart" onClick={restartGame}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Restart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;